#!/usr/bin/env python
# -*- coding: utf-8 -*-
from click import *


@command()
@option('--docs', default=False, is_flag=True, help='Generate api documentation')
@option('--help', default=False, is_flag=True, help='')
def rest(docs, help):
    if docs:
        print 'Generate Swagger documentation'
    if help:
        print '''A full stack command supports for web service application
Usages:
    --docs : Api documentation
    --app  : Skeleton application
    --db   : Database manipulation
    --help : Command line usages'''


if __name__ == '__main__':
    rest()
